title: Paula Rueda # your name (or website title) here
logo: "/images/logoc.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Industrial Engineer with an international Master’s degree in Finance. Has 6+ years of experience in financial modeling and valuation analysis, corporate finance, and project management.
  Multilingual (English, Spanish, Portuguese, and French) with strong analytical skills, detail-oriented, proactive and ability to work effectively in a fast-paced environment.
  Goes above and beyond for the team improvement, and has strong collaborative values. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/paularuedaleal/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
