title: Paula Rueda # your name (or website title) here
logo: "/images/Picture2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc in Finance with over 6 years of experience in team leadership, financial modeling, data analysis, budgeting, and forecasting.
  <br><br>
  <a href="https://www.linkedin.com/in/paularuedaleal/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.github.com/Paula52485">View My GitHub Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
